global:
  scrape_interval: 4s

scrape_configs:
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'coin-api'
    
    static_configs:
      - targets: ['host.docker.internal:5000']
