version: '3.8'

services:
  my-express-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - expressnet
    volumes:
      - .:/my-express-app
      - /my-express-app/node_modules

networks:
  expressnet:
